<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Shark IT</title>
        <link rel="icon" href="./images/logo-home.jpg" type="image/x-icon">
        <link rel="stylesheet" href="{{URL::asset('./css/style.css')}}">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700;800;900&display=swap" rel="stylesheet">
        <link
            rel="stylesheet"
            href="https://unpkg.com/swiper@8/swiper-bundle.min.css"/>
        <script src="https://kit.fontawesome.com/a3e679052b.js" crossorigin="anonymous"></script>
        <style>
            body{
                background-image: url(./images/backgroud.jpg) ;
                background-repeat:no-repeat;
                background-size:100%;
            }
        </style>
    </head>
    <body>
        <!--====Menu===-->
        <nav>
            <div class="container nav_container">
                <a href="{{url('/')}}"><h4>SHARK IT</h4></a>
                <ul class="nav_menu">
                    <li><a href="{{url('/')}}">Home</a></li>
                    <li><a href="{{url('/about')}}">About</a></li>
                    <li><a href="{{url('/Courses')}}">Courses</a></li>
                    <li><a href="{{url('/contact')}}">Contact</a></li>
                </ul>
                <button id="open-menu-btn"><i class="fa-solid fa-bars"></i></button>
                <button id="close-menu-btn"><i class="fa-solid fa-xmark"></i></button>
            </div>
        </nav>




        <!--=============
            ====HEADER===
            =============
        -->
        <header>
            <div class="container header_container">
                <div class="header_left">
                    <h1>IT training, helping to master programming languages for beginners or who want to improve on other languages</h1>
                    <p> 
                        Shark IT is a website that supports quality programming learning, smart and effective can help learners become the future programmers who are always sought after by many companies
                    </p>
                    <a href="{{route('courses')}}" class="btn btn-primary">Get Started</a>
                </div>
                <div class="header_right">
                    <div class="header_right-image">
                        <img src="./images/header.png" alt="">
                    </div>
                </div>
            </div>
        </header>


        <!--=================
            ====Categories===
            =================
        -->
        <section class="categories">
            <div class="container categories_container">
                <div class="categories_left">
                    <h1>Training</h1>
                    <p>
                        Improve your web programming skills with this 2-month course
                    </p>
                    <a href="{{route('courses')}}" class="btn">Learn More</a>
                </div>
                <div class="categories_right">
                    <article class="category">
                        <span class="category_icon"><img src="./images/html.png"></span>
                        <h5>HTML</h5>
                        <p>HTML is a markup language designed to create web pages on the World Wide Web</p>
                    </article>

                    <article class="category">
                        <span class="category_icon"><img src="./images/css.png"></span>
                        <h5>CSS</h5>
                        <p>CSS stands for Cascading Style Sheets, it is a language used to find and reformat elements generated by markup languages(HTML)</p>
                    </article>

                    <article class="category">
                        <span class="category_icon"><img src="./images/js.png"></span>
                        <h5>JAVASCRIPS</h5>
                        <p>
                            JavaScript is a website programming language, integrated and embedded in HTML to make the website more vivid</p>
                    </article>

                    <article class="category">
                        <span class="category_icon"><img src="./images/bootstrap.png"></span>
                        <h5>BOOTSTRAP</h5>
                        <p>Bootstrap is the most popular HTML, CSS, and JavaScript framework for developing responsive, mobile-first websites</p>
                    </article>

                    <article class="category">
                        <span class="category_icon"><img src="./images/sql.png"/></span>
                        <h5>SQL</h5>
                        <p>SQL is a standard language for storing, manipulating and retrieving data in databases</p>
                    </article>
                    
                    <article class="category">
                        <span class="category_img"><img src="./images/php.png"></span>
                        <h5>PHP</h5>
                        <p>PHP is a server scripting language, and a powerful tool for making dynamic and interactive Web pages</p>
                    </article>
                </div>
            </div>
        </section>

        <!--==============
            ====Courses===
            ==============
        -->
        <section class="courses">
            <h2>Courses</h2>
            <div class="container courses_container">
            @foreach($tb as $new)
                <article class="course">
                    <div class="course_image">
                        <img src="./images/course.jpg" alt="">
                    </div>
                    <div class="course_info">
                        
                        <h4>{{$new->name_courses}}</h4>
                        
                        <p>{{$new->info_courses}}</p>
                       
                        <a href="{{route('learn',$new->name_courses)}}" class="btn btn-primary">Learn More</a>
                    </div>
                </article>
                @endforeach
                
           
                
            </div>    
        </section>

        <!--===========
            ====Faqs===
            ===========
        -->
        <section class="faqs">
            <h2>Frequently Asked Questions</h2>
            <div class="container faqs_container">
                <article class="faq">
                    <div class="faq_icon"><i class="fa-solid fa-plus"></i></div>
                    <div class="question_answer">
                        <h4>What will you learn from Shark IT?</h4>
                        <p>
                            -Know how to build web interfaces<br>
                            -Know how to analyze website interface<br>
                            -Know how to self-study new knowledge<br>
                            -Know how to motivate yourself<br>
                            -Master Flexbox when building website layouts
                        </p>
                    </div>
                </article>

                <article class="faq">
                    <div class="faq_icon"><i class="fa-solid fa-plus"></i></div>
                    <div class="question_answer">
                        <h4>Is web programing difficult?</h4>
                        <p>Web programming is not difficult if you have a methodical learning path. Shark IT will help you do that. Web as well as the subjects you have been studying, from easy to advanced so that your level can be improved as quickly as possible.</p>
                    </div>
                </article>

                <article class="faq">
                    <div class="faq_icon"><i class="fa-solid fa-plus"></i></div>
                    <div class="question_answer">
                        <h4>What is the best way to learn programming?</h4>
                        <p>For most skills, some people learn better by doing, some by watching others, some by listening to podcasts, etc. This does not apply to programming. There is only one way to learn to code and that is to learn and practice every day.</p>
                    </div>
                </article>

                <article class="faq">
                    <div class="faq_icon"><i class="fa-solid fa-plus"></i></div>
                    <div class="question_answer">
                        <h4>How do I know the right course for me?</h4>
                        <p>Environment is a broad concept, in the most general perspective can be understood that are important and essential conditions for human life in general and other life coexisting with humans.</p>
                    </div>
                </article>

                <article class="faq">
                    <div class="faq_icon"><i class="fa-solid fa-plus"></i></div>
                    <div class="question_answer">
                        <h4>Job opportunities for programmers?</h4>
                        <p> 1. Web Developer: Website development specialist. Web developers will build a full-featured website.<br>
                            2. Full-Stack Developer: Full-Stack Developer is the person in charge of both the front-end to the back-end, with additional activities on the mobile side<br>
                            3. Business Analyst: Communicating and connecting the requirements from the Dev team and the business side is the task of a Business Analyst.</p>
                    </div>
                </article>

                <article class="faq">
                    <div class="faq_icon"><i class="fa-solid fa-plus"></i></div>
                    <div class="question_answer">
                        <h4>What programming language are you most proficient in?</h4>
                        <p>I am most proficient in C. because it is a basic language and the first language in the process of becoming a programmer.</p>
                    </div>
                </article>

                <article class="faq">
                    <div class="faq_icon"><i class="fa-solid fa-plus"></i></div>
                    <div class="question_answer">
                        <h4>Do you need to be good at math to learn programming?</h4>
                        <p>Environment is a broad concept, in the most general perspective can be understood that are important and essential conditions for human life in general and other life coexisting with humans.</p>
                    </div>
                </article>

                <article class="faq">
                    <div class="faq_icon"><i class="fa-solid fa-plus"></i></div>
                    <div class="question_answer">
                        <h4>Which programming language do you most want to learn?</h4>
                        <p>The language that I want to learn the most right now is html. because this is one of the main languages in the web programming process.</p>
                    </div>
                </article>
            </div>
        </section>



        <!--================
            =======Team=====
            ================
        -->
        <section class="container team_container mySwiper">
            <h2>OurTeam</h2>
            <div class="swiper-wrapper">
                <article class="team swiper-slide">
                    <div class="avatar">
                        <img src="./images/nnhi.jpg" alt="">
                    </div>
                    <div class="team_info">
                        <h5>Nguyen Ngoc Yen Nhi</h5>
                    </div>
                    <div class="team_body">
                        <p>My real name is Nguyen Ngoc Yen Nhi, everyone usually call my nickname is Annie. I was born in 2002 (20 years old). I'm currently studying at Ho Chi Minh City University of Education, majoring in information technology.</p>
                    </div>
                </article>

                <article class="team swiper-slide">
                    <div class="avatar">
                        <img src="./images/NguyenTheHoang.jpg" alt="">
                    </div>
                    <div class="team_info">
                        <h5>Nguyen The Hoang</h5>
                    </div>
                    <div class="team_body">
                        <p>Nguyen The Hoang, I was born in 2002, I can work under pressure. I often listent to music and play guitar. I'm single. I studying IT at HCM city of Education.I want to become a web designer in the future</p>
                    </div>
                </article>

                <article class="team swiper-slide">
                    <div class="avatar">
                        <img src="./images/NguyenNhatHuy.jpg" alt="">
                    </div>
                    <div class="team_info">
                        <h5>Nguyen Nhat Huy</h5>
                    </div>
                    <div class="team_body">
                        <p>My real name is Nguyen Nhat Huy, 20 years old, studying IT at Ho Chi Minh City Pedagogical School, born in 2002, my hobbies are reading, listening to music and playing games. I like to work in groups and enjoy consulting with my friends.</p>
                    </div>
                </article>

                <article class="team swiper-slide">
                    <div class="avatar">
                        <img src="./images/TranNhatTan.jpg" alt="">
                    </div>
                    <div class="team_info">
                        <h5>Tran Nhat Tan</h5>
                    </div>
                    <div class="team_body">
                        <p>My name is Tran Nhat Tan, I was born in 2002, I'm currently studying at Ho Chi Minh City University of Education. I like to play guitar and listen to music, in addition to playing the sport of football.</p>
                    </div>
                </article>

                <article class="team swiper-slide">
                    <div class="avatar">
                        <img src="./images/MaiTuQuy.jpg" alt="">
                    </div>
                    <div class="team_info">
                        <h5>Mai Tu Quy</h5>
                    </div>
                    <div class="team_body">
                        <p>My name is Mai Tu Quy, born in 2002. Currently a student of information technology, studying at Ho Chi Minh City University of Education. My hobbies are listening to music, playing games and traveling. Dream of becoming a gamer to conquer entertaining games of adventure and discovery.</p>
                    </div>
                </article>
            </div>
            <div class="swiper-pagination"></div>
        </section>



        <!--================
            =======Footer=====
            ================
        -->
        <footer class="footer">
            <div class="container footer_container">
                <div class="footer_1">
                    <a href="{{url('/')}}" class="footer_logo"><h4>SHARK IT</h4></a>
                    <p>Shark IT will provide you with the most rewarding courses</p>
                </div>

                <div class="footer_2">
                    <h4>Permalinks</h4>
                    <ul class="permalinks">
                        <li><a href="{{url('/')}}">Home</a></li>
                        <li><a href="{{url('/about')}}">About</a></li>
                        <li><a href="{{url('/Courses')}}">Courses</a></li>
                        <li><a href="{{url('/contact')}}">Contact</a></li>
                    </ul>
                </div>

                <div class="footer_3">
                    <h4>Primacy</h4>
                    <ul class="primacy">
                        <li> Privacy Policy</li>
                        <li>Terms anhd conditions</li>
                        <li> Refund Policy</li>
                    </ul>
                </div>

                <div class="footer_4">
                    <h4>Contact Us</h4>
                    <div>
                        <p>079 774 5043</p>
                        <p>nguyenngocyennhi20022@gmail.com</p>
                    </div>

                    <ul class="footer_socials">
                        <li><a href="https://www.facebook.com/people/Nny-Nhi/100033294522764/"><i class="fa-brands fa-facebook-square"></i></a></li>
                        <li><a href="https://www.instagram.com/kdi452k2/"><i class="fa-brands fa-instagram-square"></i></a></li>
                        <li><a href="https://github.com/NnyNhi2k2/"><i class="fa-brands fa-github-square"></i></a></li>
                    </ul>
                </div>
            </div>
            <div class="footer_copyright">
                <small>Copyright &copy; SHARK YouTube Tutorial</small>
            </div>
        </footer>

        <script src="./main.js"></script>
        <script src="https://unpkg.com/swiper@8/swiper-bundle.min.js"></script>


        <script>
            var swiper = new Swiper(".mySwiper", {
            slidesPerView: 1,
            spaceBetween: 30,
            pagination: {
            el: ".swiper-pagination",
            clickable: true,
            },
            // when window width is >= 600px
            breakpoints:{
                600:{
                    slidesPerView: 2,
                }
            }
        });
        </script>
    </body>
</html>